# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43a9576705b621544225ed9364ab0525523347ffa3bd9412cc3c621d0950bd55cb2e14eb4c0c0793e1171bd6af5e3b3557a921b069646d3ed436fcd6ea4764ad

test:
  secret_key_base: 90f0b7994d694a17a5330013cf1211c4d0379780c8f762cebbcbed5f41f1c337fceec9a34361b32c266a1f14718026c0c9578d9ad968ca1bc8b97931ea2e2990

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
